# --- Website information and Structure --- #

# Website information
title: Rafael Alves ITM
author: Rafael Alves

# List of links in the navigation bar
navbar-links:
  Sobre: sobre
  Redes Sociais: redes-sociais
  Blog: blog
  Floresta: floresta
  Projetos:
    - Mestrado: mestrado
    - Tutoriais do Obsidian: obsidian
    - Melhorias ao site: melhorias

# --- Footer social media links --- #

social-network-links:
  email: "rgomesal@hotmail.com"
  github: rafaelalvesitm
  twitter: rafaelalvesitm
  linkedin: rafaelalvesitm
  # youtube: channel/UCaUVPwUwNKnQ5TwGsDZwRKQ
  instagram: rafaelalvesitm
  ORCID: 0000-0002-3603-315X
  google-scholar: swKME70AAAAJ 
  lattes: "6950937359307635" 

# --- General options --- #

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%d/%m/%Y"

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 5

kramdown:
  input: GFM

collections:
  notes:
    output: true
    permalink: /:slug

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true 
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
      permalink: /floresta/:title

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock

include:
  - pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at

language: pt-BR